services:
  # NGINX
  nginx:
    depends_on:
      - app
      # - app_frontend
      - auth
    image: nginx:alpine
    container_name: integra.nginx
    tty: true
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/ssl/certs/privkey.pem
      - ./app:/var/www/app
    ports:
      - 453:443
    networks:
      integra:
        ipv4_address: 172.21.0.5
  # Keycloak PostgreSQL
  dbauth:
    image: postgres
    container_name: integra.dbauth
    tty: true
    environment:
      - POSTGRES_USER=${AUTH_DB_USERNAME}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_DATABASE}
      - POSTGRES_PORT=${AUTH_DB_PORT}
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - dbauth:/var/lib/postgresql/data
    networks:
      integra:
        ipv4_address: 172.21.0.6
  # Keycloak
  auth:
    depends_on:
      - dbauth
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    image: castorsoft/auth
    container_name: integra.auth
    tty: true
    environment:
      # Endpoints
    #   - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HOSTNAME=https://${AUTH_URL}
      - KC_HOSTNAME_ADMIN=https://${AUTH_ADMIN_URL}
      # https certs
      - KC_HTTPS_CERTIFICATE_FILE=/etc/ssl/certs/fullchain.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/ssl/certs/privkey.pem
      # DB
      - KC_DB=${AUTH_DB_CONNECTION}
      - KC_DB_URL_DATABASE=${AUTH_DB_DATABASE}
      - KC_DB_URL_HOST=${AUTH_DB_HOST}
      - KC_DB_URL_PORT=${AUTH_DB_PORT}
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=${AUTH_DB_USERNAME}
      - KC_DB_PASSWORD=${AUTH_DB_PASSWORD}
      # Starting admin user
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=yametekudasai

    restart: unless-stopped
    volumes:
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/ssl/certs/privkey.pem
    networks:
      integra:
        ipv4_address: 172.21.0.10
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.app
    image: castorsoft/app
    container_name: integra.app
    tty: true
    volumes:
      - ./app:/var/www/app
    restart: unless-stopped
    networks:
      integra:
        ipv4_address: 172.21.0.20
    extra_hosts:
      - "auth.castorsoft.com.br:172.17.0.1"
  db:
    image: postgres
    container_name: integra.db
    tty: true
    environment:
      - POSTGRES_USER=${APP_DB_USERNAME}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_DATABASE}
      - POSTGRES_PORT=${APP_DB_PORT}
    ports:
      - "5434:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      integra:
        ipv4_address: 172.21.0.7
networks:
  integra:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
volumes:
  dbauth:
    driver: local
  db:
    driver: local